appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Rlfs92ClYnojL62aa8XP9n8dbIDP263HB7aHtGV5Hv3tizqgpSC/Cs84fGkuoARJKW9w/53GBtEJoXalBWR30Aut2DByPpy+bgStvnzBt9j5omxns5E8GK3Vn0kTtAOjjpl/h/oYttBPskPfrPz29+UnMZPuo1YKD9JSm//FRKZZdufn960YYzDwTeO0U7porZaYS4S1f9XQ6c78Vz7cW3hSItRWE7OGrPHDsIUH8gmmh15lh2TzLebEUUUakhZVjM3uLJOkDm6FrFcXqh47ZoC6O2k+zDEv5BZxULRpgIHonM1ptW3OzTZaOuuQh1UgXnVTurNtZArzS6orb33KDNWtuYAax/zC0abscqYOOxqMa6HoX4yecMd33GLlNSWDFNhmCNP2E62P+JqIdmtarib2yOfp34Ol12RwU3REsl/EcZZTSiMCAVqGZkG7TrAXifv+3EaS80E1XSh4AhYNxLhx825fFY6Zm8CSAoXr5erBUZ+ivKWl/HKfFfN5Zhn+Pzfbmewc0LfOSeI5Xmk/oSoIO1Xr8jR3zRxWppGzh8Jmh3J1Ck9qUdnB4JPbruIJ0JaTWkKW3ISuMm+sunX/KiqOe0cmivytk/KxFbrOwi1gtiQt9hynZWhmTyel+g/TeRGkqEUgaHJxotXA6hA0zxDFgY6k9kqLg/DYCGT9ZS4=
